[package]
name = "utrace"
version = "0.1.0"
edition = "2021"


[dependencies]
critical-section = "1.1.2"
defmt = "0.3.6"
utrace_macros = { path = "../utrace_macros" }

[dev-dependencies]
proptest = "1.4.0"

[features]
default = ["std"]
std = []
