[package]
name = "utrace_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gimli = { version = "0.28.1", features = ["read", "std", "read-all", "fallible-iterator", "endian-reader", "read-core"] } 
memmap2 = "0.9.4"
object = "0.27"
