[package]
name = "utrace_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = {version = "1.0.79", features = ["span-locations"]}
quote = "1.0.35"
syn = {version="2.0.55", features=["full"]}
darling = "0.20.8"
